#!/bin/bash

echo "This starts up all the servers.  Checks so it won't start a second process."
# panama
mongoconf=/usr/local/etc/mongod.conf
if [ ! -f "$mongoconf" ]
then mongoconf=/dvl/mongodb/mongod.conf
	   # flores
fi
MONGODCMD="mongod --config $mongoconf"
#MONGODCMD='mongod --config /usr/local/etc/mongod.conf'
echo mongo launch cmd: $MONGODCMD


# make sure I'm in the same dir as this script
cd `dirname $0`

# start mongo for rodex server to work
if ! pgrep -f mongod
then
	echo ":::::::::::::::::::::::::::::::::::: Starting up mongo DB server"
	$MONGODCMD &
	sleep 2
else
	echo "mongod already running"
fi


# must start rodex server for react webapp to run
if ! pgrep -f rodexServer
then 
	echo ":::::::::::::::::::::::::::::::::::: Starting up backend rodex server"
	./rodexServer.js &
	sleep 2
else
	echo "rodex server already running"
fi

# now run react server
if ! pgrep -f recruit-o-dex/node_modules/react-scripts/script
then 
	echo ":::::::::::::::::::::::::::::::::::: Starting up React Server"
	PORT=3300 EDITOR= TERM= node_modules/.bin/react-scripts start &
	sleep 2
else
	echo "react server already running"
fi
echo "Go surf to http://localhost:3300"

